Repository GSG-FC03/API-Team8, pull requests merged in 2021-07, with the labels that each got.

#2 1 createfilestrcture
  CSS/.css
  index.html
  script/main.js
Labels: done

#8 7 img folder
  CSS/.css
  CSS/style.css
  img/1.jpg
  img/2.jpg
  img/3.jpg
  img/refresh.svg
  index.html
Labels: waiting-review

#4 Coding the main page as HTML
  index.html
Labels: waiting-review

#10 9link api in javascript
  index.html
  script/main.js
Labels: a waitting reviwe

#13 12 responsive design
  CSS/style.css
  index.html
Labels: waiting-review
